---
# Empty task file - to be populated later 

- name: Set environment variables for data fetching
  set_fact:
    fetch_env:
      ES_HOST: "{{ es_url }}"
      ES_INDEX: "{{ server_compliance_metrics_index }}"
      ES_USERNAME: "{{ ES_USERNAME }}"
      ES_PASSWORD: "{{ ES_PASSWORD }}"
      OUTPUT_FILE: "{{ current_raw_data_file }}"

- name: Execute fetch_data.py script
  ansible.builtin.command:
    cmd: "python3 {{ role_path }}/files/fetch_data.py"
  environment: "{{ fetch_env }}"
  register: fetch_result
  failed_when: fetch_result.rc != 0

- name: Display fetch results
  debug:
    msg:
    - "Fetch completed for issue type: {{ current_issue_type }}"
    - "Output file: {{ current_raw_data_file }}"
    - "Exit code: {{ fetch_result.rc }}"
    - "Output: {{ fetch_result.stdout_lines }}"
  when: fetch_result.stdout_lines is defined

- name: Check if raw data file was created
  stat:
    path: "{{ current_raw_data_file }}"
  register: raw_data_stat

- name: Fail if no data was fetched
  fail:
    msg: "No data file was created for {{ current_issue_type }}"
  when: not raw_data_stat.stat.exists
